# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotenv < Formula
  desc "Better dotenv–from the creator of `dotenv`"
  homepage "https://github.com/dotenv-org/dotenv"
  url "https://github.com/dotenv-org/dotenv/archive/refs/tags/v0.2.19.tar.gz"
  sha256 "1f9e8fdf0431d464feb7c84d32a3445bcf0f99f40830e38979d2878145b2e4f5"

  on_macos do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.19/dotenv-0.2.19-darwin-amd64.tar.gz"
      sha256 "135d997dc1e760cb73250e12154b341b246c5a92c45e57cf6d528d7f8aab1008"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.19/dotenv-0.2.19-darwin-arm64.tar.gz"
      sha256 "44c6e2b1c96420c5fe932daca98ffe7a53fe863ae445225de7e54fae6f4a3c16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.19/dotenv-0.2.19-linux-amd64.tar.gz"
      sha256 "355b7075375c2b75cce67879a1fe320b72c494d7da6c77ddae59aca44100ad90"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.19/dotenv-0.2.19-linux-arm64.tar.gz"
      sha256 "e28c56e90e02cbfb32d0f2b3b619279df609a42e69a8b383df9dfacc33df48ea"
    end
  end

  def install
    bin.install "dotenv"; bin.install_symlink "dotenv" => "git-dotenv";
  end
end
